(part "SQJ148EP-T1_GE3"
    (packageRef "SQJ148EPT1_GE3")
    (interface
        (port "1" (symbPinId 1) (portName "S_1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "S_2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "S_3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "G") (portType INOUT))
        (port "5" (symbPinId 5) (portName "D_1") (portType INOUT))
        (port "6" (symbPinId 6) (portName "D_2") (portType INOUT))
        (port "7" (symbPinId 7) (portName "D_3") (portType INOUT))
        (port "8" (symbPinId 8) (portName "D_4") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Manufacturer_Name" "Vishay")
    (property "Manufacturer_Part_Number" "SQJ148EP-T1_GE3")
    (property "Mouser_Part_Number" "78-SQJ148EP-T1_GE3")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Vishay-Siliconix/SQJ148EP-T1_GE3?qs=G1ssh2j%252Bqz5yrigayqaTsg%3D%3D")
    (property "Arrow_Part_Number" "SQJ148EP-T1_GE3")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/sqj148ep-t1-ge3/vishay?utm_currency=USD&region=nac")
    (property "Description" "MOSFET N Ch 40Vds 20Vgs AEC-Q101 Qualified")
    (property "Datasheet_Link" "http://www.vishay.com/docs/75162/sqj148ep.pdf")
    (property "symbolName1" "SQJ148EP-T1_GE3")
)
