# Generated by the VisualDSP++ IDDE

# Note:  Any changes made to this Makefile will be lost the next time the
# matching project file is loaded into the IDDE.  If you wish to preserve
# changes, rename this file and run it externally to the IDDE.

# The syntax of this Makefile is such that GNU Make v3.77 or higher is
# required.

# The current working directory should be the directory in which this
# Makefile resides.

# Supported targets:
#     LSBFaraOptimizare_Debug
#     LSBFaraOptimizare_Debug_clean

# Define this variable if you wish to run this Makefile on a host
# other than the host that created it and VisualDSP++ may be installed
# in a different directory.

ADI_DSP=C:\Program Files (x86)\Analog Devices\VisualDSP 5.1.2


# $VDSP is a gmake-friendly version of ADI_DIR

empty:=
space:= $(empty) $(empty)
VDSP_INTERMEDIATE=$(subst \,/,$(ADI_DSP))
VDSP=$(subst $(space),\$(space),$(VDSP_INTERMEDIATE))

RM=cmd /C del /F /Q

#
# Begin "LSBFaraOptimizare_Debug" configuration
#

ifeq ($(MAKECMDGOALS),LSBFaraOptimizare_Debug)

LSBFaraOptimizare_Debug : ./Debug/LSBFaraOptimizare.dxe 

Debug/LSBFaraOptimizare.doj :LSBFaraOptimizare.c $(VDSP)/Blackfin/include/stdio.h $(VDSP)/Blackfin/include/yvals.h $(VDSP)/Blackfin/include/string.h audio_data.dat 
	@echo ".\LSBFaraOptimizare.c"
	$(VDSP)/ccblkfn.exe -c .\LSBFaraOptimizare.c -file-attr ProjectName=LSBFaraOptimizare -g -structs-do-not-overlap -no-multiline -double-size-32 -decls-strong -warn-protos -proc ADSP-BF533 -o .\Debug\LSBFaraOptimizare.doj -MM

./Debug/marcare_lsb.doj :Debug/marcare_lsb.c 
	@echo ".\Debug\marcare_lsb.c"
	$(VDSP)/ccblkfn.exe -c .\Debug\marcare_lsb.c -file-attr ProjectName=LSBFaraOptimizare -g -structs-do-not-overlap -no-multiline -double-size-32 -decls-strong -warn-protos -proc ADSP-BF533 -o .\Debug\marcare_lsb.doj -MM

./Debug/LSBFaraOptimizare.dxe :$(VDSP)/Blackfin/ldf/adsp-BF533.ldf $(VDSP)/Blackfin/lib/bf532_rev_0.5/crtsf532y.doj ./Debug/LSBFaraOptimizare.doj ./Debug/marcare_lsb.doj $(VDSP)/Blackfin/lib/bf532_rev_0.5/__initsbsz532.doj $(VDSP)/Blackfin/lib/cplbtab533.doj $(VDSP)/Blackfin/lib/bf532_rev_0.5/crtn532y.doj $(VDSP)/Blackfin/lib/bf532_rev_0.5/libsmall532y.dlb $(VDSP)/Blackfin/lib/bf532_rev_0.5/libio532y.dlb $(VDSP)/Blackfin/lib/bf532_rev_0.5/libc532y.dlb $(VDSP)/Blackfin/lib/bf532_rev_0.5/librt_fileio532y.dlb $(VDSP)/Blackfin/lib/bf532_rev_0.5/libevent532y.dlb $(VDSP)/Blackfin/lib/bf532_rev_0.5/libcpp532y.dlb $(VDSP)/Blackfin/lib/bf532_rev_0.5/libf64ieee532y.dlb $(VDSP)/Blackfin/lib/bf532_rev_0.5/libdsp532y.dlb $(VDSP)/Blackfin/lib/bf532_rev_0.5/libsftflt532y.dlb $(VDSP)/Blackfin/lib/bf532_rev_0.5/libetsi532y.dlb $(VDSP)/Blackfin/lib/bf532_rev_0.5/Debug/libssl532y.dlb $(VDSP)/Blackfin/lib/bf532_rev_0.5/Debug/libdrv532y.dlb $(VDSP)/Blackfin/lib/bf532_rev_0.5/Debug/libusb532y.dlb $(VDSP)/Blackfin/lib/bf532_rev_0.5/libprofile532y.dlb 
	@echo "Linking..."
	$(VDSP)/ccblkfn.exe .\Debug\LSBFaraOptimizare.doj .\Debug\marcare_lsb.doj -L .\Debug -add-debug-libpaths -flags-link -od,.\Debug -o .\Debug\LSBFaraOptimizare.dxe -proc ADSP-BF533 -MM

endif

ifeq ($(MAKECMDGOALS),LSBFaraOptimizare_Debug_clean)

LSBFaraOptimizare_Debug_clean:
	-$(RM) "Debug\LSBFaraOptimizare.doj"
	-$(RM) ".\Debug\marcare_lsb.doj"
	-$(RM) ".\Debug\LSBFaraOptimizare.dxe"
	-$(RM) ".\Debug\*.ipa"
	-$(RM) ".\Debug\*.opa"
	-$(RM) ".\Debug\*.ti"
	-$(RM) ".\Debug\*.pgi"
	-$(RM) ".\*.rbld"

endif


