(part "RD3L150SNTL1"
    (packageRef "RD3P175SNFRATL")
    (interface
        (port "1" (symbPinId 1) (portName "G") (portType INOUT))
        (port "2" (symbPinId 2) (portName "D") (portType INOUT))
        (port "3" (symbPinId 3) (portName "S") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Manufacturer_Name" "ROHM Semiconductor")
    (property "Manufacturer_Part_Number" "RD3L150SNTL1")
    (property "Mouser_Part_Number" "755-RD3L150SNTL1")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/ROHM-Semiconductor/RD3L150SNTL1?qs=YCa%2FAAYMW03JC0hEdrDgqA%3D%3D")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "MOSFET Nch 60V 15A TO-252 (DPAK)")
    (property "Datasheet_Link" "https://fscdn.rohm.com/en/products/databook/datasheet/discrete/transistor/mosfet/rd3l150sntl-e.pdf")
    (property "symbolName1" "RD3L150SNTL1")
)
